version: '3.7'

services:
  # Inspecting tools
  # kafdrop:
  #  image: obsidiandynamics/kafdrop
  #  container_name: kafdrop
  #  ports:
  #    - "9000:9000"
  #  environment:
  #   JVM_OPTS: "-Xms32M -Xmx64M"
  #   KAFKA_BROKERCONNECT: ${HOST_K1}:${PORT_EXT_K1},${HOST_K2}:${PORT_EXT_K2},${HOST_K3}:${PORT_EXT_K3}
  #   SERVER_SERVLET_CONTEXTPATH: "/"
  akhq:
    # build:
    #   context: .
    image: tchiotludo/akhq
    restart: unless-stopped
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "${HOST_K1}:${PORT_EXT_K1},${HOST_K2}:${PORT_EXT_K2},${HOST_K3}:${PORT_EXT_K3}"
              schema-registry:
                url: "http://schema-registry:8085"
              connect:
                - name: "connect-1"
                  url: "http://${HOST_K1}:${PORT_CONN_1:-9101}"

    ports:
      - ${PORT_AKHQ:-8000}:8080
    
  schema-registry:
    ## Warning: set min in sync replicas to 2 if using 3 node cluster to ensure durable schema commits
    image: confluentinc/cp-schema-registry:${CONFLUENT_VERSION:-latest}
    restart: unless-stopped
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'PLAINTEXT://${HOST_K1}:${PORT_EXT_K1},PLAINTEXT://${HOST_K2}:${PORT_EXT_K2},PLAINTEXT://${HOST_K3}:${PORT_EXT_K3}'
      SCHEMA_REGISTRY_HOST_NAME: 'schema-registry'
      SCHEMA_REGISTRY_LISTENERS: 'http://0.0.0.0:8085'  # API requests come in on this
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: 'INFO'

      # SCHEMA_RESTISTRY_SCHEMA_COMPATIBILITY_LEVEL: 'backward'
    ports:
     - ${PORT_SCHEMA:-8002}:8085
  
  ksqldb:
    image: confluentinc/cp-ksqldb-server:${CONFLUENT_VERSION:-latest}
    restart: unless-stopped
    depends_on:
      - schema-registry
    ports:
      - 8088:8088
    environment:
      KSQL_BOOTSTRAP_SERVERS: '${HOST_K1}:${PORT_EXT_K1},${HOST_K2}:${PORT_EXT_K2},${HOST_K3}:${PORT_EXT_K3}'
      KSQL_LISTENERS: 'http://0.0.0.0:8088'
      KSQL_KSQL_SERVICE_ID: 'ksql'
      KSQL_KSQL_SCHEMA_REGISTRY_URL: 'http://schema-registry:8085'
      KSQL_KSQL_CONNECT_URL: "http://${HOST_K1}:${PORT_CONN_1:-9101}"
      KSQL_KSQL_SINK_PARTITIONS: '1'
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_REPLICATION_FACTOR: '1'

  kafka-rest:
    image: confluentinc/cp-kafka-rest:${CONFLUENT_VERSION:-latest}
    depends_on:
      - schema-registry
    ports:
      - 8082:8082
    environment:
      KAFKA_REST_HOST_NAME: kafka-rest
      KAFKA_REST_BOOTSTRAP_SERVERS: '${HOST_K1}:${PORT_EXT_K1},${HOST_K2}:${PORT_EXT_K2},${HOST_K3}:${PORT_EXT_K3}'
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
      KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://schema-registry:8085'

# kafka rest api

