#######
# 3 Node Kafka Cluster - All three nodes need to know about each other for cluster stability in the event of a failure
# Node    Node ID                   Controller Port           External Port           Host IP
# 1       ${NODE_ID_K1:-1}          ${PORT_CTL_K1:-9192}      ${PORT_EXT_K1:-9194}    ${HOST_K1}
# 2       ${NODE_ID_K2:-2}          ${PORT_CTL_K2:-9292}      ${PORT_EXT_K2:-9294}    ${HOST_K2}
# 3       ${NODE_ID_K3:-3}          ${PORT_CTL_K3:-9392}      ${PORT_EXT_K3:-9394}    ${HOST_K3}
#
# Inside  9092                      9094 (This isn't exposed to the outside world)
#################
# Kafka Node 2
#################
version: "3.8"
services:
  kafka2:
    image: bitnami/kafka:3.7
    env_file:
      - .env.k2
    environment:
      # Specific to this node
      - KAFKA_CFG_NODE_ID=${NODE_ID_K2:-2}
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9092,EXTERNAL://${HOST_K2}:${PORT_EXT_K2:-9294}
      
      # Generic to all
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=${NODE_ID_K1:-1}@${HOST_K1}:${PORT_CTL_K1:-9193},${NODE_ID_K2:-2}@${HOST_K2}:${PORT_CTL_K2:-9293},${NODE_ID_K3:-3}@${HOST_K3}:${PORT_CTL_K3:-9393}
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_KRAFT_CLUSTER_ID=${ENVIRONMENT}_KAFKA_CLUSTER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=EXTERNAL

    ports:
      - "${PORT_CTL_K2:-9293}:9093"
      - "${PORT_EXT_K2:-9294}:9094"

#   volumes:
#    - kafka_data:/bitnami/kafka

# volumes:
#   kafka_data:
#     driver: local
#     driver_opts:
#       type: none
