# First Kafka 
version: "3.8"
services:
  image: bitnami:kafka:3.7
  environment:
    - KAFKA_CFG_NODE_ID=${NODE_ID}
    - KAFKA_CFG_PROCESS_ROLES:controller,broker
    - KAFKA_CFG_LISTENERS=CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
    - KAFKA_CFG_ADVERTISED_LISTENERS=CONTROLLER://${HOST_IP}:${CONTROLLER_PORT},EXTERNAL://${HOST_IP}:${EXTERNAL_PORT}
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL,PLAINTEXT
    - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=${NODE_ID}@${HOST_IP}:${CONTROLLER_PORT}
    - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    - KAFKA_KRAFT_CLUSTER_ID=${ENVIRONMENT}_KAFKA_CLUSTER
  ports:
    - "${CONTROLLER_PORT}:9093"
    - "${EXTERNAL_PORT}:9094"

#   volumes:
#    - kafka_data:/bitnami/kafka

# volumes:
#   kafka_data:
#     driver: local
#     driver_opts:
#       type: none