## Note: This stack should be deployed with the name 'ks_b4' for proper hostname resolution if Schema Registry is added in the future.
##
#######
# 5 Node Kafka Cluster - All five nodes need to know about each other for cluster stability in the event of a failure
# Node    Node ID                   Controller Port           External Port           Host IP
# 1       ${NODE_ID_K1:-1}          ${PORT_CTL_K1:-40111}     ${PORT_EXT_K1:-40110}   ${HOST_K1}    ${PORT_PLAIN_K1:-40112}    ${PORT_METRICS_K1:-40115}
# 2       ${NODE_ID_K2:-2}          ${PORT_CTL_K2:-40121}     ${PORT_EXT_K2:-40120}   ${HOST_K2}    ${PORT_PLAIN_K2:-40122}    ${PORT_METRICS_K2:-40125}
# 3       ${NODE_ID_K3:-3}          ${PORT_CTL_K3:-40131}     ${PORT_EXT_K3:-40130}   ${HOST_K3}    ${PORT_PLAIN_K3:-40132}    ${PORT_METRICS_K3:-40135}
# 4       ${NODE_ID_K4:-4}          ${PORT_CTL_K4:-40141}     ${PORT_EXT_K4:-40140}   ${HOST_K4}    ${PORT_PLAIN_K4:-40142}    ${PORT_METRICS_K4:-40145}
# 5       ${NODE_ID_K5:-5}          ${PORT_CTL_K5:-40151}     ${PORT_EXT_K5:-40150}   ${HOST_K5}    ${PORT_PLAIN_K5:-40152}    ${PORT_METRICS_K5:-40155}
#
# Inside  9092 (PLAINTEXT), 9093 (CONTROLLER), 9094 (EXTERNAL)
#
## Setup
# docker node update --label-add docker-server-2=true node2
##
#################
# Kafka Node 4
#################
version: "3.8"
services:
  broker:
    image: bitnami/kafka:3.7
    networks:
      - ks_schema_network
    environment:
      # Specific to this node
      - KAFKA_CFG_NODE_ID=${NODE_ID_K4}
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${HOST_K4}:${PORT_PLAIN_K4},EXTERNAL://${HOST_K4}:${PORT_EXT_K4}

      # Generic to all
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=${NODE_ID_K1}@${HOST_K1}:${PORT_CTL_K1},${NODE_ID_K2}@${HOST_K2}:${PORT_CTL_K2},${NODE_ID_K3}@${HOST_K3}:${PORT_CTL_K3},${NODE_ID_K4}@${HOST_K4}:${PORT_CTL_K4},${NODE_ID_K5}@${HOST_K5}:${PORT_CTL_K5}
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_KRAFT_CLUSTER_ID=${ENVIRONMENT}_KAFKA_CLUSTER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=EXTERNAL
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=3

    ports:
      - "${PORT_PLAIN_K4}:9092"
      - "${PORT_CTL_K4}:9093"
      - "${PORT_EXT_K4}:9094"
    deploy:
      placement:
        constraints:
          - node.labels.docker-server-2 == true
      resources:
        limits:
          memory: 10G
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9094 --list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - kafka-data-4:/bitnami/kafka

  schema:
    image: confluentinc/cp-schema-registry:${CONFLUENT_VERSION:-latest}
    restart: unless-stopped
    depends_on:
      - broker
    networks:
      - ks_schema_network
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'PLAINTEXT://${HOST_K1}:${PORT_EXT_K1},PLAINTEXT://${HOST_K2}:${PORT_EXT_K2},PLAINTEXT://${HOST_K3}:${PORT_EXT_K3}'
      SCHEMA_REGISTRY_HOST_NAME: 'ks_b4_schema'
      SCHEMA_REGISTRY_LISTENERS: 'http://0.0.0.0:8085'
      SCHEMA_REGISTRY_ADVERTISED_LISTENERS: 'http://${HOST_K4}:${PORT_SCHEMA4}'
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: 'INFO'
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: '_schemas'
      SCHEMA_REGISTRY_GROUP_ID: 'schema-registry-cluster'
      SCHEMA_REGISTRY_MASTER_ELIGIBILITY: 'true'

      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR: '3'
      SCHEMA_REGISTRY_KAFKASTORE_TIMEOUT_MS: '15000'
      SCHEMA_REGISTRY_KAFKASTORE_INIT_TIMEOUT_MS: '60000'
    ports:
     - ${PORT_SCHEMA4}:8085
    deploy:
      placement:
        constraints:
          - node.labels.docker-server-2 == true
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://0.0.0.0:8085/subjects || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  kafka-data-4:

networks:
  ks_schema_network:
    external: true
