version: "3.8"

services:
  kafdrop:
   image: obsidiandynamics/kafdrop
   container_name: kafdrop
   ports:
     - "9000:9000"
   environment:
    JVM_OPTS: "-Xms32M -Xmx64M"
    KAFKA_BROKERCONNECT: kafka:9092
    SERVER_SERVLET_CONTEXTPATH: "/"

  kafka:
    image: docker.io/bitnami/kafka:3.7
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.86.183:9092  # The host IP was important

      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT

      # Increase maximum message size
      - KAFKA_CFG_MESSAGE_MAX_BYTES=1000000000
      - KAFKA_CFG_MAX_REQUEST_SIZE=1000000000
      - KAFKA_CFG_MAX_PARTITION_FETCH_BYTES=1000000000

volumes:
  kafka_data:
    driver: local