version: '3.7'

services:
  # Inspecting tools
  kafdrop:
   image: obsidiandynamics/kafdrop
   container_name: kafdrop
   ports:
     - "9000:9000"
   environment:
    JVM_OPTS: "-Xms32M -Xmx64M"
    KAFKA_BROKERCONNECT: ${HOST_K1}:${PORT_EXT_K1},${HOST_K2}:${PORT_EXT_K2},${HOST_K3}:${PORT_EXT_K3}
    SERVER_SERVLET_CONTEXTPATH: "/"
  akhq:
    # build:
    #   context: .
    image: tchiotludo/akhq
    restart: unless-stopped
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "${HOST_K1}:${PORT_EXT_K1}"
              schema-registry:
                url: "http://schema-registry:8085"
              connect:
                - name: "connect"
                  url: "http://connect:8083"

    ports:
      - 8001:8080
    # links:
    #   - kafka
    #   - schema-registry
