version: '3.7'

services:
  # Inspecting tools
  # kafdrop:
  #  image: obsidiandynamics/kafdrop
  #  container_name: kafdrop
  #  ports:
  #    - "9000:9000"
  #  environment:
  #   JVM_OPTS: "-Xms32M -Xmx64M"
  #   KAFKA_BROKERCONNECT: ${HOST_K1}:${PORT_EXT_K1},${HOST_K2}:${PORT_EXT_K2},${HOST_K3}:${PORT_EXT_K3}
  #   SERVER_SERVLET_CONTEXTPATH: "/"
  akhq:
    # build:
    #   context: .
    image: tchiotludo/akhq
    restart: unless-stopped
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "${HOST_K1}:${PORT_EXT_K1}"
              schema-registry:
                url: "http://schema-registry:8085"
      # connect:
      #   - name: "connect"
      #     url: "http://connect:8083"

    ports:
      - 8001:8080
    # links:
    #   - kafka
    #   - schema-registry
  schema-registry:
    image: confluentinc/cp-schema-registry:${CONFLUENT_VERSION:-latest}
    restart: unless-stopped
    # depends_on:
    #   - kafka
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'PLAINTEXT://${HOST_K1}:${PORT_EXT_K1}'
      SCHEMA_REGISTRY_HOST_NAME: 'schema-registry'
      SCHEMA_REGISTRY_LISTENERS: 'http://0.0.0.0:8085'  # API requests come in on this
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: 'INFO'

      # SCHEMA_RESTISTRY_SCHEMA_COMPATIBILITY_LEVEL: 'backward'
    ports:
     - ${PORT_SCHEMA:-8002}:8085
  # connect:
  #   image: confluentinc/cp-kafka-connect:${CONFLUENT_VERSION:-latest}
  #   restart: unless-stopped
  #   depends_on:
  #     - kafka
  #     - schema-registry
  #   environment:
  #     CONNECT_BOOTSTRAP_SERVERS: 'kafka:9092'
  #     CONNECT_REST_PORT: '8083'
  #     CONNECT_REST_LISTENERS: 'http://0.0.0.0:8083'
  #     CONNECT_REST_ADVERTISED_HOST_NAME: 'connect'
  #     CONNECT_CONFIG_STORAGE_TOPIC: '__connect-config'
  #     CONNECT_OFFSET_STORAGE_TOPIC: '__connect-offsets'
  #     CONNECT_STATUS_STORAGE_TOPIC: '__connect-status'
  #     CONNECT_GROUP_ID: 'kafka-connect'
  #     CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: 'true'
  #     CONNECT_KEY_CONVERTER: 'io.confluent.connect.avro.AvroConverter'
  #     CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8085'
  #     CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: 'true'
  #     CONNECT_VALUE_CONVERTER: 'io.confluent.connect.avro.AvroConverter'
  #     CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8085'
  #     CONNECT_INTERNAL_KEY_CONVERTER: 'org.apache.kafka.connect.json.JsonConverter'
  #     CONNECT_INTERNAL_VALUE_CONVERTER: 'org.apache.kafka.connect.json.JsonConverter'
  #     CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: '1'
  #     CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: '1'
  #     CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: '1'
  #     CONNECT_PLUGIN_PATH: ' /usr/share/java/'

  # ksqldb:
  #   image: confluentinc/cp-ksqldb-server:${CONFLUENT_VERSION:-latest}
  #   restart: unless-stopped
  #   depends_on:
  #     - kafka
  #     - connect
  #     - schema-registry
  #   ports:
  #     - 8088:8088
  #   environment:
  #     KSQL_BOOTSTRAP_SERVERS: 'kafka:9092'
  #     KSQL_LISTENERS: 'http://0.0.0.0:8088'
  #     KSQL_KSQL_SERVICE_ID: 'ksql'
  #     KSQL_KSQL_SCHEMA_REGISTRY_URL: 'http://schema-registry:8085'
  #     KSQL_KSQL_CONNECT_URL: 'http://connect:8083'
  #     KSQL_KSQL_SINK_PARTITIONS: '1'
  #     KSQL_KSQL_LOGGING_PROCESSING_TOPIC_REPLICATION_FACTOR: '1'
