all:
  vars:
    ansible_connection: ssh
    ansible_user: ituser
    ansible_become: true
    ansible_ssh_private_key_file: ~/.ssh/rsa.key
    ansible_ssh_common_args: -o StrictHostKeyChecking=no

zookeeper:
  hosts:
    slc-host1.domain.com:

kafka_broker:
  hosts:
    slc-host2.domain.com:
    slc-host3.domain.com:
    slc-host4.domain.com:

schema_registry:
  hosts:
    slc-host5.domain.com:

ksql:
  hosts:
    slc-host5.domain.com:

kafka_connect:
  hosts:
    slc-host5.domain.com:
      vars:
        kafka_connect_confluent_hub_plugins:
          - confluentinc/kafka-connect-datagen:0.4.0

control_center:
  hosts:
    slc-host6.domain.com:
